# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c26151d8f7614822fa3d204f90006f7c2c8c7120651ee9298a174dea47fda84ea948d6417ee32266b368fa88d390b77d04b000111fdaa57cd0e98e6d31b5de

test:
  secret_key_base: 2185a45e011850f5b5a86130344c7f42f96c4e8f1ce6eaa13443d6feb629b89ca6c602a24133434a755d25fb3d723e7cf436e5cf7519b19635bd694336cacf7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
